"""
BSSSubmitter — CodedTool
Submits TMF921 Intent JSON to BSS (Etiya mock on port 8002).
Uses sly_data to keep API key out of the chat stream.
Endpoint is driven by BSS_ENDPOINT env var — zero code change for mock→real swap.

Security design (per canonical order flow):
- Intent_ID is generated by TMF921Generator before this call — embedded in TMF921
- API_Key is generated by BSS on receipt — stored in sly_data only, never in chat
- Customer only ever sees Intent_ID and BSS state in the chat reply
"""
import json
import os
from typing import Any, Dict
import httpx
from neuro_san.interfaces.coded_tool import CodedTool


class BSSSubmitter(CodedTool):
    """
    HTTP POST of TMF921 Intent to BSS endpoint.
    Mock endpoint: http://localhost:8002/mock/bss/intent
    Real endpoint: set BSS_ENDPOINT env var — no code change required.

    What is returned to front man (and shown to customer):
      - Intent Reference (intentRef) — safe to show
      - BSS State (acknowledged) — safe to show
      - TMF921 JSON — safe to show (no credentials inside)

    What is NOT returned to front man:
      - API Key — stored in sly_data only, never enters chat stream
    """

    async def async_invoke(self, args: Dict[str, Any], sly_data: Dict[str, Any]) -> Any:
        bss_endpoint = os.environ.get(
            "BSS_ENDPOINT",
            "http://localhost:8002/mock/bss/intent"
        )

        tmf921_json_str = args.get("tmf921_json", "")
        if not tmf921_json_str:
            return {
                "status": "ERROR",
                "message": "❌ No TMF921 JSON provided to BSS submitter."
            }

        try:
            # Llama models sometimes wrap JSON in markdown code blocks
            # or add explanatory text before/after the JSON object.
            # Strip all of that before parsing.
            import re
            clean = tmf921_json_str.strip()

            # Remove markdown code fences: ```json ... ``` or ``` ... ```
            clean = re.sub(r'^```(?:json)?\s*', '', clean, flags=re.IGNORECASE)
            clean = re.sub(r'\s*```$', '', clean)
            clean = clean.strip()

            # If there is text before the first { or after the last }, trim it
            start = clean.find('{')
            end   = clean.rfind('}')
            if start != -1 and end != -1 and end > start:
                clean = clean[start:end + 1]

            tmf921 = json.loads(clean)

            # Keep tmf921_json_str as the clean version for display
            tmf921_json_str = json.dumps(tmf921, indent=2)

        except json.JSONDecodeError as e:
            return {
                "status": "ERROR",
                "message": f"❌ Invalid TMF921 JSON: {str(e)}"
            }

        intent_id = tmf921.get("id", "unknown")

        try:
            async with httpx.AsyncClient(timeout=10.0) as client:
                response = await client.post(
                    bss_endpoint,
                    json=tmf921,
                    headers={"Content-Type": "application/json"}
                )

            if response.status_code in (200, 201, 202):
                data       = response.json()
                intent_ref = data.get("intentRef", intent_id)
                api_key    = data.get("api_key", "BSS-PENDING")
                state      = data.get("state", "acknowledged")

                # ── API key stored in sly_data — never enters chat stream ────
                # Per canonical order flow: customer never sees API_Key.
                # BSS owns it. LLM Router validates against BSS directly.
                sly_data["bss_api_key"] = api_key
                sly_data["intent_ref"]  = intent_ref
                sly_data["intent_id"]   = intent_id

                return {
                    "status":      "SUCCESS",
                    "intent_ref":  intent_ref,
                    "intent_id":   intent_id,
                    "state":       state,
                    "tmf921_json": tmf921_json_str,
                    "message": (
                        f"✅ Order submitted successfully.\n"
                        f"Intent Reference: {intent_ref}\n"
                        f"BSS State: {state}\n\n"
                        f"Your order is now being processed. "
                        f"Track the status in the Orders page using your Intent ID: {intent_id}\n\n"
                        f"TMF921 Intent document:\n```json\n{tmf921_json_str}\n```"
                    )
                }
                # NOTE: api_key deliberately omitted from return dict and message.
                # It is secured in sly_data for internal handover — not for display.

            else:
                return {
                    "status":      "ERROR",
                    "http_status": response.status_code,
                    "intent_id":   intent_id,
                    "tmf921_json": tmf921_json_str,
                    "message": (
                        f"❌ BSS returned HTTP {response.status_code}: {response.text[:200]}\n\n"
                        f"The TMF921 Intent document was generated successfully "
                        f"but could not be submitted. Here it is for your reference:\n"
                        f"```json\n{tmf921_json_str}\n```"
                    )
                }

        except httpx.ConnectError:
            return {
                "status":      "ERROR",
                "intent_id":   intent_id,
                "tmf921_json": tmf921_json_str,
                "message": (
                    f"❌ Could not connect to BSS at {bss_endpoint}. "
                    f"Is the mock vendor server running? (uvicorn main:app --port 8002)\n\n"
                    f"The TMF921 Intent document was generated successfully. "
                    f"Here it is for your reference:\n"
                    f"```json\n{tmf921_json_str}\n```"
                )
            }

        except httpx.TimeoutException:
            return {
                "status":      "ERROR",
                "intent_id":   intent_id,
                "tmf921_json": tmf921_json_str,
                "message": (
                    f"❌ BSS request timed out at {bss_endpoint}.\n\n"
                    f"The TMF921 Intent document was generated. "
                    f"Here it is for your reference:\n"
                    f"```json\n{tmf921_json_str}\n```"
                )
            }

        except Exception as e:
            return {
                "status":      "ERROR",
                "intent_id":   intent_id,
                "tmf921_json": tmf921_json_str,
                "message": (
                    f"❌ Unexpected error submitting to BSS: {str(e)}\n\n"
                    f"The TMF921 Intent document was generated. "
                    f"Here it is for your reference:\n"
                    f"```json\n{tmf921_json_str}\n```"
                )
            }